{
 "title": "Stromverbrauch tipower-portal",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "tablename",
    "query": "SELECT DISTINCT SUBSTRING_INDEX(TABLE_NAME, '_', 1) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = DATABASE() AND TABLE_TYPE = 'BASE TABLE';"
   }
  ]
 },
 "panels": [
  {
   "title": "Summe Verbrauch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  value AS \"Stromverbrauch\"\nFROM ${tablename}_day\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Aktueller Verbrauch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  value AS \"Stromverbrauch\"\nFROM ${tablename}_day\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Durchschnittlicher Verbrauch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  value AS \"Stromverbrauch\"\nFROM ${tablename}_day\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Maximalverbrauch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  value AS \"Stromverbrauch\"\nFROM ${tablename}_day\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Minimalverbrauch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  value AS \"Stromverbrauch\"\nFROM ${tablename}_day\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Stromverbrauch pro Tag",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  value AS \"Stromverbrauch\"\nFROM ${tablename}_day\nWHERE\n  $__timeFilter(time)\nORDER BY time;"
    },
    {
     "rawSql": "SELECT\n  DATE_ADD(time, INTERVAL 1 YEAR) AS \"time\",\n  value AS \"Stromverbrauch letztes Jahr\"\nFROM ${tablename}_day\nWHERE\n  time >= DATE_ADD($__timeFrom(), INTERVAL -1 YEAR) AND \n  time <= DATE_ADD($__timeTo(), INTERVAL -1 YEAR)\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Stromverbrauch pro Tag",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  value AS \"Stromverbrauch\"\nFROM ${tablename}_day\nWHERE\n  $__timeFilter(time,24h)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Stromverbrauch pro 15 Minuten",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  value AS \"Stromverbrauch\"\nFROM ${tablename}_15m\nWHERE\n  $__timeFilter(time)\nORDER BY time"
    }
   ]
  }
 ]
}